### PR TITLE
Swap Location and Date of an Event on the Event Dashboard

### PR DESCRIPTION
**Pull request by patrick-du**
[Notion ticket](https://www.notion.so/uwblueprintexecs/Swap-the-location-and-date-of-the-event-on-the-event-dashboard-e6a9a590727945d4b48f3fa9dc0148ca)

## Changes
- Swapped positioning of the location and date of an event

## Screenshots
Before
image
After
image

## Testing
- Check that the positions of location and date are swapped

before opening PR
- [x] check notion ticket
- [x] run linter
- [x] go through file diff

filling out PR
- [x] descriptive title
- [x] update `notion ticket` link
- [ ] update `figma link`
- [x] fill out `Changes`
  - [ ] \(optional) add inline comments in diff
- [x] fill out `Testing`
- [x] \(optional) add `Screenshots`
- [x] assign yourself to the PR

after opening PR
- [x] link PR to notion ticket
- [x] make sure build passes
- [x] move ticket to `In PR`
- [x] ping `@ps` in `#paramedics-dev`

### CODE REVIEW

**Review by petorsong — APPROVED** [review]
🍔

**Review by jesskeepswimming — APPROVED** [review]
image
image

Not sure if these errors are due to errors from this PR, but for some reason, choosing December 12 as the date shows up as "undefined", and the address is always Ezra. furthermore, the page breaks if you press any key on the date input, which may be misleading because the date input is a text field.

If these issues aren't due to this PR, we can open some bug tickets!

**Comment by petorsong** [comment]
> 
> 
> image
> image
> 
> Not sure if these errors are due to errors from this PR, but for some reason, choosing December 12 as the date shows up as "undefined", and the address is always Ezra. furthermore, the page breaks if you press any key on the date input, which may be misleading because the date input is a text field.
> 
> If these issues aren't due to this PR, we can open some bug tickets!

we should definitely look into these, looks to be separate bugs but we should attempt to repro - on my end:
- dec 12: can't repro
- address always Ezra: expected - we're currently hard coding this (will be fixed with aaron's location work)
- pressing keys on the date input: we have a ticket open for this already (https://www.notion.so/uwblueprintexecs/Auth-Landing-Clean-up-69ae713e56a1443993822ead17dcd414)

**Comment by petorsong** [comment]
all issues have been addressed here as well #49

**Pull request merged**
