### PR TITLE
Patient Cleanup

### PR DESCRIPTION
**Pull request by aaronabraham311**
[Notion ticket](https://www.notion.so/uwblueprintexecs/396370c5e09f4c28bc7f455a7e84c908?v=3751aa62a2594c74b7e0ecb363304c24&p=7108d3eee3cf4c96893e3de358ae5a55)

## Changes
- Fixed 2/3 `useEffect` errors, but this will be addressed in a later ticket
- Checked that routing after cancel or submitting is working properly 
- Made patient status un-toggable (a user cannot have a empty status unless previously deleted)
- Added mandatory validation for age

## Testing
- Check that routing is working correctly: any submission (deletion/completion) or cancelling should take you to the CCP dashboard
- Make sure that status buttons are not toggalable (as in, if you were to select the status for one patient, you cannot click again and assign no status)
- Try to submit a patient with no age. The submission should not work and an appropriate message should show.

before opening PR
- [x] check notion ticket
- [x] run linter
- [x] go through file diff

filling out PR
- [x] descriptive title
- [x] update `notion ticket` link
- [x] fill out `Changes`
  - [ ] \(optional) add inline comments in diff
- [x] fill out `Testing`
- [x] \(optional) add `Screenshots`
- [x] assign yourself to the PR

after opening PR
- [x] link PR to notion ticket
- [x] move ticket to `In PR`
- [ ] make sure build passes
- [x] ping `@ps` in `#paramedics-dev`

### CODE REVIEW

**Comment by sarafong** [comment]
this is more of a requirement question but for age, wouldn't DOB make more sense/be more useful? like what if they're <1 year

**Comment by petorsong** [comment]
> 
> 
> this is more of a requirement question but for age, wouldn't DOB make more sense/be more useful? like what if they're <1 year

date of birth is pretty much personally identifiable information (PII), so we're not allowed to store that

**Review by petorsong — DISMISSED** [review]
looks good

it would be nice to have only the numeric keyboard pop up when trying to input the age (for ipad) - this can potentially be done using `inputmode=numeric`, i would play around with it to see if it's easy to implement, otherwise we can put it in a different ticket maybe
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

**Comment by aaronabraham311** [comment]
If you want to test out the numeric input, please visit this link: https://stackoverflow.com/questions/45760350/how-to-make-react-app-preview-on-mobile. It wouldn't work for me but maybe you two could have more success.

**Review by petorsong — COMMENTED** [review]
tried tunneling to test out the numeric input field on my (android) phone and ipad - couldn't get it to work on either; would be nice to have provided it's very simple, otherwise we'll just forget about it and not include any changes related to the numeric field

@sarafong here's the doc about tunneling if you want to try it as well (if you have an ios device, preferably an ipad)
https://www.notion.so/uwblueprintexecs/Tunneling-872fa180fce14d3b9c5cc35c17e5a49a

**Comment by sarafong** [comment]
code looks good, tested on ios (iphone) and couldn't get the numeric keyboard to trigger either

**Review by sarafong — APPROVED** [review]

**Review by petorsong — APPROVED** [review]
numeric stuff was not fruitful, we may revisit later on - my bad for blocking this PR based on that

**Pull request merged**
